package i18n

// native name of cultures.
var cultureNativeNames = map[string]string{
	"af-ZA":       "Afrikaans (Suid Afrika)",
	"am-ET":       "አማርኛ (ኢትዮጵያ)",
	"ar-AE":       "العربية (الإمارات العربية المتحدة)",
	"ar-BH":       "العربية (البحرين)",
	"ar-DZ":       "العربية (الجزائر)",
	"ar-EG":       "العربية (مصر)",
	"ar-IQ":       "العربية (العراق)",
	"ar-JO":       "العربية (الأردن)",
	"ar-KW":       "العربية (الكويت)",
	"ar-LB":       "العربية (لبنان)",
	"ar-LY":       "العربية (ليبيا)",
	"ar-MA":       "العربية (المملكة المغربية)",
	"arn-CL":      "Mapudungun (Chile)",
	"ar-OM":       "العربية (عمان)",
	"ar-QA":       "العربية (قطر)",
	"ar-SA":       "العربية (المملكة العربية السعودية)",
	"ar-SY":       "العربية (سوريا)",
	"ar-TN":       "العربية (تونس)",
	"ar-YE":       "العربية (اليمن)",
	"as-IN":       "অসমীয়া (ভাৰত)",
	"az-Cyrl-AZ":  "Азәрбајҹан (Азәрбајҹан)",
	"az-Latn-AZ":  "Azərbaycan­ılı (Azərbaycan)",
	"ba-RU":       "Башҡорт (Россия)",
	"be-BY":       "Беларускі (Беларусь)",
	"bg-BG":       "български (България)",
	"bn-BD":       "বাংলা (বাংলাদেশ)",
	"bn-IN":       "বাংলা (ভারত)",
	"bo-CN":       "བོད་ཡིག (ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ།)",
	"br-FR":       "brezhoneg (Frañs)",
	"bs-Cyrl-BA":  "босански (Босна и Херцеговина)",
	"bs-Latn-BA":  "bosanski (Bosna i Hercegovina)",
	"ca-ES":       "català (català)",
	"co-FR":       "Corsu (France)",
	"cs-CZ":       "čeština (Česká republika)",
	"cy-GB":       "Cymraeg (y Deyrnas Unedig)",
	"da-DK":       "dansk (Danmark)",
	"de-AT":       "Deutsch (Österreich)",
	"de-CH":       "Deutsch (Schweiz)",
	"de-DE":       "Deutsch (Deutschland)",
	"de-LI":       "Deutsch (Liechtenstein)",
	"de-LU":       "Deutsch (Luxemburg)",
	"dsb-DE":      "dolnoserbšćina (Nimska)",
	"dv-MV":       "ދިވެހިބަސް (ދިވެހި ރާއްޖެ)",
	"el-GR":       "Ελληνικά (Ελλάδα)",
	"en-029":      "English (Caribbean)",
	"en-AU":       "English (Australia)",
	"en-BZ":       "English (Belize)",
	"en-CA":       "English (Canada)",
	"en-GB":       "English (United Kingdom)",
	"en-IE":       "English (Ireland)",
	"en-IN":       "English (India)",
	"en-JM":       "English (Jamaica)",
	"en-MY":       "English (Malaysia)",
	"en-NZ":       "English (New Zealand)",
	"en-PH":       "English (Philippines)",
	"en-SG":       "English (Singapore)",
	"en-TT":       "English (Trinidad y Tobago)",
	"en-US":       "English (United States)",
	"en-ZA":       "English (South Africa)",
	"en-ZW":       "English (Zimbabwe)",
	"es-AR":       "Español (Argentina)",
	"es-BO":       "Español (Bolivia)",
	"es-CL":       "Español (Chile)",
	"es-CO":       "Español (Colombia)",
	"es-CR":       "Español (Costa Rica)",
	"es-DO":       "Español (República Dominicana)",
	"es-EC":       "Español (Ecuador)",
	"es-ES":       "Español (España, alfabetización internacional)",
	"es-GT":       "Español (Guatemala)",
	"es-HN":       "Español (Honduras)",
	"es-MX":       "Español (México)",
	"es-NI":       "Español (Nicaragua)",
	"es-PA":       "Español (Panamá)",
	"es-PE":       "Español (Perú)",
	"es-PR":       "Español (Puerto Rico)",
	"es-PY":       "Español (Paraguay)",
	"es-SV":       "Español (El Salvador)",
	"es-US":       "Español (Estados Unidos)",
	"es-UY":       "Español (Uruguay)",
	"es-VE":       "Español (Republica Bolivariana de Venezuela)",
	"et-EE":       "eesti (Eesti)",
	"eu-ES":       "euskara (euskara)",
	"fa-IR":       "فارسى (ایران)",
	"fi-FI":       "suomi (Suomi)",
	"fil-PH":      "Filipino (Pilipinas)",
	"fo-FO":       "føroyskt (Føroyar)",
	"fr-BE":       "français (Belgique)",
	"fr-CA":       "français (Canada)",
	"fr-CH":       "français (Suisse)",
	"fr-FR":       "français (France)",
	"fr-LU":       "français (Luxembourg)",
	"fr-MC":       "français (Principauté de Monaco)",
	"fy-NL":       "Frysk (Nederlân)",
	"ga-IE":       "Gaeilge (Éire)",
	"gd-GB":       "Gàidhlig (An Rìoghachd Aonaichte)",
	"gl-ES":       "galego (galego)",
	"gsw-FR":      "Elsässisch (Frànkrisch)",
	"gu-IN":       "ગુજરાતી (ભારત)",
	"ha-Latn-NG":  "Hausa (Nigeria)",
	"he-IL":       "עברית (ישראל)",
	"hi-IN":       "हिंदी (भारत)",
	"hr-BA":       "hrvatski (Bosna i Hercegovina)",
	"hr-HR":       "hrvatski (Hrvatska)",
	"hsb-DE":      "hornjoserbšćina (Němska)",
	"hu-HU":       "magyar (Magyarország)",
	"hy-AM":       "Հայերեն (Հայաստան)",
	"id-ID":       "Bahasa Indonesia (Indonesia)",
	"ig-NG":       "Igbo (Nigeria)",
	"ii-CN":       "ꆈꌠꁱꂷ (ꍏꉸꏓꂱꇭꉼꇩ)",
	"is-IS":       "íslenska (Ísland)",
	"it-CH":       "italiano (Svizzera)",
	"it-IT":       "italiano (Italia)",
	"iu-Cans-CA":  "ᐃᓄᒃᑎᑐᑦ (ᑲᓇᑕᒥ)",
	"iu-Latn-CA":  "Inuktitut (Kanatami)",
	"ja-JP":       "日本語 (日本)",
	"ka-GE":       "ქართული (საქართველო)",
	"kk-KZ":       "Қазақ (Қазақстан)",
	"kl-GL":       "kalaallisut (Kalaallit Nunaat)",
	"km-KH":       "ខ្មែរ (កម្ពុជា)",
	"kn-IN":       "ಕನ್ನಡ (ಭಾರತ)",
	"kok-IN":      "कोंकणी (भारत)",
	"ko-KR":       "한국어 (대한민국)",
	"ky-KG":       "Кыргыз (Кыргызстан)",
	"lb-LU":       "Lëtzebuergesch (Luxembourg)",
	"lo-LA":       "ລາວ (ສ.ປ.ປ. ລາວ)",
	"lt-LT":       "lietuvių (Lietuva)",
	"lv-LV":       "latviešu (Latvija)",
	"mi-NZ":       "Reo Māori (Aotearoa)",
	"mk-MK":       "македонски јазик (Македонија)",
	"ml-IN":       "മലയാളം (ഭാരതം)",
	"mn-MN":       "Монгол хэл (Монгол улс)",
	"mn-Mong-CN":  "ᠮᠤᠨᠭᠭᠤᠯ ᠬᠡᠯᠡ (ᠪᠦᠭᠦᠳᠡ ᠨᠠᠢᠷᠠᠮᠳᠠᠬᠤ ᠳᠤᠮᠳᠠᠳᠤ ᠠᠷᠠᠳ ᠣᠯᠣᠰ)",
	"moh-CA":      "Kanien'kéha",
	"mr-IN":       "मराठी (भारत)",
	"ms-BN":       "Bahasa Melayu (Brunei Darussalam)",
	"ms-MY":       "Bahasa Melayu (Malaysia)",
	"mt-MT":       "Malti (Malta)",
	"nb-NO":       "norsk, bokmål (Norge)",
	"ne-NP":       "नेपाली (नेपाल)",
	"nl-BE":       "Nederlands (België)",
	"nl-NL":       "Nederlands (Nederland)",
	"nn-NO":       "norsk, nynorsk (Noreg)",
	"nso-ZA":      "Sesotho sa Leboa (Afrika Borwa)",
	"oc-FR":       "Occitan (França)",
	"or-IN":       "ଓଡ଼ିଆ (ଭାରତ)",
	"pa-IN":       "ਪੰਜਾਬੀ (ਭਾਰਤ)",
	"pl-PL":       "polski (Polska)",
	"prs-AF":      "درى (افغانستان)",
	"ps-AF":       "پښتو (افغانستان)",
	"pt-BR":       "Português (Brasil)",
	"pt-PT":       "português (Portugal)",
	"qut-GT":      "K'iche (Guatemala)",
	"quz-BO":      "runasimi (Qullasuyu)",
	"quz-EC":      "runasimi (Ecuador)",
	"quz-PE":      "runasimi (Piruw)",
	"rm-CH":       "Rumantsch (Svizra)",
	"ro-RO":       "română (România)",
	"ru-RU":       "русский (Россия)",
	"rw-RW":       "Kinyarwanda (Rwanda)",
	"sah-RU":      "саха (Россия)",
	"sa-IN":       "संस्कृत (भारतम्)",
	"se-FI":       "davvisámegiella (Suopma)",
	"se-NO":       "davvisámegiella (Norga)",
	"se-SE":       "davvisámegiella (Ruoŧŧa)",
	"si-LK":       "සිංහල (ශ්‍රී ලංකා)",
	"sk-SK":       "slovenčina (Slovenská republika)",
	"sl-SI":       "slovenski (Slovenija)",
	"sma-NO":      "åarjelsaemiengiele (Nöörje)",
	"sma-SE":      "åarjelsaemiengiele (Sveerje)",
	"smj-NO":      "julevusámegiella (Vuodna)",
	"smj-SE":      "julevusámegiella (Svierik)",
	"smn-FI":      "sämikielâ (Suomâ)",
	"sms-FI":      "sääm´ǩiõll (Lää´ddjânnam)",
	"sq-AL":       "shqipe (Shqipëria)",
	"sr-Cyrl-BA":  "српски (Босна и Херцеговина)",
	"sr-Cyrl-CS":  "српски (Србија и Црна Гора (Претходно))",
	"sr-Cyrl-ME":  "српски (Црна Гора)",
	"sr-Cyrl-RS":  "српски (Србија)",
	"sr-Latn-BA":  "srpski (Bosna i Hercegovina)",
	"sr-Latn-CS":  "srpski (Srbija i Crna Gora (Prethodno))",
	"sr-Latn-ME":  "srpski (Crna Gora)",
	"sr-Latn-RS":  "srpski (Srbija)",
	"sv-FI":       "svenska (Finland)",
	"sv-SE":       "svenska (Sverige)",
	"sw-KE":       "Kiswahili (Kenya)",
	"syr-SY":      "ܣܘܪܝܝܐ (سوريا)",
	"ta-IN":       "தமிழ் (இந்தியா)",
	"te-IN":       "తెలుగు (భారత దేశం)",
	"tg-Cyrl-TJ":  "Тоҷикӣ (Тоҷикистон)",
	"th-TH":       "ไทย (ไทย)",
	"tk-TM":       "türkmençe (Türkmenistan)",
	"tn-ZA":       "Setswana (Aforika Borwa)",
	"tr-TR":       "Türkçe (Türkiye)",
	"tt-RU":       "Татар (Россия)",
	"tzm-Latn-DZ": "Tamazight (Djazaïr)",
	"ug-CN":       "ئۇيغۇرچە (جۇڭخۇا خەلق جۇمھۇرىيىتى)",
	"uk-UA":       "українська (Україна)",
	"ur-PK":       "اُردو (پاکستان)",
	"uz-Cyrl-UZ":  "Ўзбек (Ўзбекистон)",
	"uz-Latn-UZ":  "U'zbek (U'zbekiston Respublikasi)",
	"vi-VN":       "Tiếng Việt (Việt Nam)",
	"wo-SN":       "Wolof (Sénégal)",
	"xh-ZA":       "isiXhosa (uMzantsi Afrika)",
	"yo-NG":       "Yoruba (Nigeria)",
	"zh-CN":       "中文(中华人民共和国)",
	"zh-HK":       "中文(香港特別行政區)",
	"zh-MO":       "中文(澳門特別行政區)",
	"zh-SG":       "中文(新加坡)",
	"zh-TW":       "中文(台灣)",
	"zu-ZA":       "isiZulu (iNingizimu Afrika)",
}
